- import_tasks: pgsql_version.yml

- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always

- name: Generate replication slot names
  set_fact:
    pgsqlrep_primary_slot_name: "slot{{ ansible_loop.index }}"
  loop: "{{ groups[pgsqlrep_group_name] }}"
  loop_control:
    extended: yes
  delegate_to: "{{ item }}"
  delegate_facts: yes
  run_once: yes
  when: hostvars[item]['pgsqlrep_primary_slot_name'] is undefined

- include_tasks: "{{ pgsqlrep_role }}.yml"
  when: pgsqlrep_role != 'skip'
