Vagrant.configure(2) do |config|

  # config.dns.tld = "vagrant.dev"

  # CentOS 6
  config.vm.define "ROLENAME-el6" do |centos6|
    centos6.vm.box = "geerlingguy/centos6"
    centos6.vm.hostname = "ROLENAME-centos6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ROLENAME-el6"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # CentOS 7
  config.vm.define "ROLENAME-el7" do |centos7|
    centos7.vm.box = "geerlingguy/centos7"
    centos7.vm.hostname = "ROLENAME-centos7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ROLENAME-el7"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # Ubuntu 12.04
  config.vm.define "ROLENAME-ub12" do |node|
    node.vm.box = "geerlingguy/ubuntu1204"
    node.vm.hostname = "ROLENAME-ub12"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ROLENAME-ub12"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # Ubuntu 14.04
  config.vm.define "ROLENAME-ub14" do |ub14|
    ub14.vm.box = "geerlingguy/ubuntu1404"
    ub14.vm.hostname = "ROLENAME-ub14"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ROLENAME-ub14"
      vbox.cpus = 1
      vbox.memory = 256
    end
  end

  # Ubuntu 16.04
  config.vm.define "ROLENAME-ub16" do |ub16|
    ub16.vm.box = "geerlingguy/ubuntu1604"
    ub16.vm.hostname = "ROLENAME-ub16"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ROLENAME-ub16"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
