Vagrant.configure(2) do |config|

  config.ssh.insert_key = false

  config.vm.define "tower1" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "tower1"
    centos7.vm.network "private_network", ip: "10.77.1.11"
    config.vm.synced_folder '../../postgresql-replication', '/etc/ansible/roles/postgres-replication'
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "tower1"
      vbox.cpus = 4
      vbox.memory = 2048
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = 'vagrant.yml'
      ansible.inventory_path = 'hosts'
    end
  end

  config.vm.define "psql-master-centos7" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "psql-master-centos7"
    centos7.vm.network "private_network", ip: "10.78.1.17"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "psql-master-centos7"
      vbox.cpus = 2
      vbox.memory = 1024
    end
  end

  config.vm.define "psql-slave-centos7" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "psql-slave-centos7"
    centos7.vm.network "private_network", ip: "10.78.1.18"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "psql-slave-centos7"
      vbox.cpus = 2
      vbox.memory = 1024
    end
  end

end
