extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments-indentation: disable
  document-start: disable
  line-length: disable
  truthy: disable

ignore: |
  molecule/default/roles
